export class ProductArray {
  Vegetables = [
    'Brinjal', 'Ridge Gourd',
    'Snake Gourd',
    'Capsicum',
    'Cabbage',
    'Cauliflower',
    'Carrot',
    'Green Peas',
    'Lemon',
    'Onion',
    'Garlic',
    'Potato',
    'Tomato',
    'Beans',
    'Cucumber',
    'Drum Stick',
    'Ladies Finger',
    'Raddish',
    'Green Chilli',
    'Bitter Gourd',
    'Ash Gourd',
    'Bottle Gourd',
    'Pumpkin',
    'Beetroot',
    'Field Beans',
    'Pineapple',
    'Pomegranate',
    'Banana',
    'Banana-raw',
    'Mango',
    'Grapes',
    'Jackfruit',
    'Guava',
    'Water Melon',
    'Musk Melon',
    'Apple'	,
    'Dates',
    'Orange',
    'Papaya'];
}
